/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitsCirurgicosRouteImport } from './routes/kits-cirurgicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsCirurgicosRoute = KitsCirurgicosRouteImport.update({
  id: '/kits-cirurgicos',
  path: '/kits-cirurgicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kits-cirurgicos': typeof KitsCirurgicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kits-cirurgicos': typeof KitsCirurgicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kits-cirurgicos': typeof KitsCirurgicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kits-cirurgicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kits-cirurgicos'
  id: '__root__' | '/' | '/kits-cirurgicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitsCirurgicosRoute: typeof KitsCirurgicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits-cirurgicos': {
      id: '/kits-cirurgicos'
      path: '/kits-cirurgicos'
      fullPath: '/kits-cirurgicos'
      preLoaderRoute: typeof KitsCirurgicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitsCirurgicosRoute: KitsCirurgicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
