/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as CasosClinicosRouteImport } from './routes/casos-clinicos'
import { Route as CatalogosRouteImport } from './routes/catalogos'
import { Route as GuiaDeTorqueRouteImport } from './routes/guia-de-torque'
import { Route as ImplantesRouteImport } from './routes/implantes'
import { Route as InstrucoesDeUsoRouteImport } from './routes/instrucoes-de-uso'
import { Route as KitsCirurgicosRouteImport } from './routes/kits-cirurgicos'
import { Route as ProtocolosTecnicosRouteImport } from './routes/protocolos-tecnicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosClinicosRoute = CasosClinicosRouteImport.update({
  id: '/casos-clinicos',
  path: '/casos-clinicos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosRoute = CatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeTorqueRoute = GuiaDeTorqueRouteImport.update({
  id: '/guia-de-torque',
  path: '/guia-de-torque',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantesRoute = ImplantesRouteImport.update({
  id: '/implantes',
  path: '/implantes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrucoesDeUsoRoute = InstrucoesDeUsoRouteImport.update({
  id: '/instrucoes-de-uso',
  path: '/instrucoes-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsCirurgicosRoute = KitsCirurgicosRouteImport.update({
  id: '/kits-cirurgicos',
  path: '/kits-cirurgicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosTecnicosRoute = ProtocolosTecnicosRouteImport.update({
  id: '/protocolos-tecnicos',
  path: '/protocolos-tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/casos-clinicos': typeof CasosClinicosRoute
  '/catalogos': typeof CatalogosRoute
  '/guia-de-torque': typeof GuiaDeTorqueRoute
  '/implantes': typeof ImplantesRoute
  '/instrucoes-de-uso': typeof InstrucoesDeUsoRoute
  '/kits-cirurgicos': typeof KitsCirurgicosRoute
  '/protocolos-tecnicos': typeof ProtocolosTecnicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/casos-clinicos': typeof CasosClinicosRoute
  '/catalogos': typeof CatalogosRoute
  '/guia-de-torque': typeof GuiaDeTorqueRoute
  '/implantes': typeof ImplantesRoute
  '/instrucoes-de-uso': typeof InstrucoesDeUsoRoute
  '/kits-cirurgicos': typeof KitsCirurgicosRoute
  '/protocolos-tecnicos': typeof ProtocolosTecnicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/casos-clinicos': typeof CasosClinicosRoute
  '/catalogos': typeof CatalogosRoute
  '/guia-de-torque': typeof GuiaDeTorqueRoute
  '/implantes': typeof ImplantesRoute
  '/instrucoes-de-uso': typeof InstrucoesDeUsoRoute
  '/kits-cirurgicos': typeof KitsCirurgicosRoute
  '/protocolos-tecnicos': typeof ProtocolosTecnicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos'
    | '/casos-clinicos'
    | '/catalogos'
    | '/guia-de-torque'
    | '/implantes'
    | '/instrucoes-de-uso'
    | '/kits-cirurgicos'
    | '/protocolos-tecnicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos'
    | '/casos-clinicos'
    | '/catalogos'
    | '/guia-de-torque'
    | '/implantes'
    | '/instrucoes-de-uso'
    | '/kits-cirurgicos'
    | '/protocolos-tecnicos'
  id:
    | '__root__'
    | '/'
    | '/artigos'
    | '/casos-clinicos'
    | '/catalogos'
    | '/guia-de-torque'
    | '/implantes'
    | '/instrucoes-de-uso'
    | '/kits-cirurgicos'
    | '/protocolos-tecnicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosRoute: typeof ArtigosRoute
  CasosClinicosRoute: typeof CasosClinicosRoute
  CatalogosRoute: typeof CatalogosRoute
  GuiaDeTorqueRoute: typeof GuiaDeTorqueRoute
  ImplantesRoute: typeof ImplantesRoute
  InstrucoesDeUsoRoute: typeof InstrucoesDeUsoRoute
  KitsCirurgicosRoute: typeof KitsCirurgicosRoute
  ProtocolosTecnicosRoute: typeof ProtocolosTecnicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-clinicos': {
      id: '/casos-clinicos'
      path: '/casos-clinicos'
      fullPath: '/casos-clinicos'
      preLoaderRoute: typeof CasosClinicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos': {
      id: '/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof CatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-torque': {
      id: '/guia-de-torque'
      path: '/guia-de-torque'
      fullPath: '/guia-de-torque'
      preLoaderRoute: typeof GuiaDeTorqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantes': {
      id: '/implantes'
      path: '/implantes'
      fullPath: '/implantes'
      preLoaderRoute: typeof ImplantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrucoes-de-uso': {
      id: '/instrucoes-de-uso'
      path: '/instrucoes-de-uso'
      fullPath: '/instrucoes-de-uso'
      preLoaderRoute: typeof InstrucoesDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits-cirurgicos': {
      id: '/kits-cirurgicos'
      path: '/kits-cirurgicos'
      fullPath: '/kits-cirurgicos'
      preLoaderRoute: typeof KitsCirurgicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos-tecnicos': {
      id: '/protocolos-tecnicos'
      path: '/protocolos-tecnicos'
      fullPath: '/protocolos-tecnicos'
      preLoaderRoute: typeof ProtocolosTecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosRoute: ArtigosRoute,
  CasosClinicosRoute: CasosClinicosRoute,
  CatalogosRoute: CatalogosRoute,
  GuiaDeTorqueRoute: GuiaDeTorqueRoute,
  ImplantesRoute: ImplantesRoute,
  InstrucoesDeUsoRoute: InstrucoesDeUsoRoute,
  KitsCirurgicosRoute: KitsCirurgicosRoute,
  ProtocolosTecnicosRoute: ProtocolosTecnicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
